image: ubuntu

build_script:
- ./install.on.ubuntu.sh
- ./check.packages.sh
- curl -O https://buildroot.org/downloads/buildroot-2018.02.4.tar.gz
- tar -zxf buildroot-2018.02.4.tar.gz
- cd buildroot-2018.02.4
- ../make.qemu_x86_defconfig.sh
- ls -lh output/images/


artifacts:
- path: buildroot-2018.02.4/output/images/bzImage
- path: buildroot-2018.02.4/output/images/rootfs.ext2
